export const SHOWLOADING='SHOWLOADING'
export const HIDELOADING='HIDELOADING'
export const ISBACK = 'ISBACK' 
export const ISBACKFALSE = 'ISBACKFALSE'
export const ISSHOWSEARCHSHOW = 'ISSHOWSEARCHSHOW'
export const ISSHOWSEARCH = 'ISSHOWSEARCH'
export const AUDIOSHOW ='AUDIOSHOW'
export const SRCID ='SRCID'
export const ISPLAYING ='ISPLAYING';
export const NOPLAYING ='NOPLAYING';
export const ISSHOWCOLLECT ='ISSHOWCOLLECT';

export const GETCOLLECT ='GETCOLLECT';
export const CLEAR ='CLEAR';
export const SET_PLAY_MODE ='SET_PLAY_MODE';
export const SET_PLAYLIST ='SET_PLAYLIST';